### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by rubiin** [TheNightmareX/tasked#1]
Please add some unit tests. Would be very helpful if you could help me with unit testing the repository

**Comment by Char2sGu** [comment]
ah yeah this repository is indeed lack of tests because this project was actually just for practicing Angular and NestJS at the begining.

I'm currently working on some other projects related to [DeepKit](https://github.com/deepkit/deepkit-framework). Both unit tests and integration tests will no longer be a problem once I pick up this project. ^_^

**Comment by Char2sGu** [comment]
btw i don't quite understand about "help you unit testing this repository", are you writing tests for this repository?

**Comment by rubiin** [comment]
@TheNightmareX regarding the deepkit . Which one is the repo. I am starting out with deepkit as well mostly the types

**Comment by Char2sGu** [comment]
sorry the repo is currently made private as I'm not satisfied with its cleanliness. Actually, despite of many bugs, DeepKit gives me a much better DX than Nest, thus I'm not quite sure whether I'll pick up these Nest stuff one day :D
